In [1]:
import pandas as pd
df_usuarios = pd.read_csv('usuarios.csv')
df_compras = pd.read_csv('compras.csv')

In [2]:
display(df_compras)
display(df_usuarios)

   id_compra  id_usuario        produto       valor data_compra
0        101           1       Notebook  R$ 3500.00  2026-01-10
1        102           2     Smartphone     2100.50  2026/01/12
2        103           1          Mouse   R$ 150.00  2026-01-15
3        104           3        Teclado         NaN  2026-01-20
4        105           4        Monitor     1200.00  2026-01-22
5        106           6  Cadeira Gamer   R$ 950.00  2026-01-25

,id_usuario,nome,email,cpf,data_cadastro
0,1,Isaque Silva,isaque.silva@email.com,123.456.789-00,2025-01-15
1,2,maria santos,maria.santos@outlook.com,98765432100,2025-02-20
2,3,CARLOS OLIVEIRA,carlos.oli@gmail.com,456.123.789-11,2025-03-05
3,4,Ana Costa,ana.costa@email.com,78945612300,2025-03-12
4,5,Isaque Silva,isaque.silva@email.com,123.456.789-00,2025-01-15
5,6,Juliana Lima,juliana.lima@Hotmail.com,22233344455,2025-04-01

## LIMPANDO E TRATANDO A TABELA DE USUÁRIOS

In [3]:
df_usuarios = df_usuarios.drop_duplicates()
df_usuarios = df_usuarios.drop(columns=['index'], errors='ignore')
df_usuarios['nome'] = df_usuarios['nome'].str.strip()
df_usuarios['cpf'] = df_usuarios['cpf'].str.replace('-', '').str.replace('.', '')
df_usuarios['cpf'] = pd.to_numeric(df_usuarios['cpf'])

In [4]:
df_usuarios['data_cadastro'] = pd.to_datetime(df_usuarios['data_cadastro'])
df_usuarios.info()

df_usuarios['nome'] = df_usuarios['nome'].str.title()
display(df_usuarios)

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id_usuario     6 non-null      int64
 1   nome           6 non-null      str
 2   email          6 non-null      str
 3   cpf            6 non-null      int64
 4   data_cadastro  6 non-null      datetime64[us]
dtypes: datetime64[us](1), int64(2), str(2)
memory usage: 372.0 bytes

,id_usuario,nome,email,cpf,data_cadastro
0,1,Isaque Silva,isaque.silva@email.com,12345678900,2025-01-15
1,2,Maria Santos,maria.santos@outlook.com,98765432100,2025-02-20
2,3,Carlos Oliveira,carlos.oli@gmail.com,45612378911,2025-03-05
3,4,Ana Costa,ana.costa@email.com,78945612300,2025-03-12
4,5,Isaque Silva,isaque.silva@email.com,12345678900,2025-01-15
5,6,Juliana Lima,juliana.lima@Hotmail.com,22233344455,2025-04-01

## LIMPANDO E TRATANDO A TABELA DE COMPRAS

In [5]:
df_compras['valor'] = df_compras['valor'].str.replace('R$', '')
df_compras['data_compra'] = df_compras['data_compra'].str.replace('/', '-')
df_compras['valor'] = pd.to_numeric(df_compras['valor'])
df_compras['data_compra'] = pd.to_datetime(df_compras['data_compra'])
df_compras['valor'] = df_compras['valor'].fillna(df_compras['valor'].mean())
display(df_compras)
df_compras.info()

   id_compra  id_usuario        produto   valor data_compra
0        101           1       Notebook  3500.0  2026-01-10
1        102           2     Smartphone  2100.5  2026-01-12
2        103           1          Mouse   150.0  2026-01-15
3        104           3        Teclado  1580.1  2026-01-20
4        105           4        Monitor  1200.0  2026-01-22
5        106           6  Cadeira Gamer   950.0  2026-01-25

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id_compra    6 non-null      int64
 1   id_usuario   6 non-null      int64
 2   produto      6 non-null      str
 3   valor        6 non-null      float64
 4   data_compra  6 non-null      datetime64[us]
dtypes: datetime64[us](1), float64(1), int64(2), str(1)
memory usage: 372.0 bytes

In [6]:
df_usuarios.to_csv('usuarios_limpos.csv', index=False)
df_compras.to_csv('compras_limpas.csv', index=False)